language: ruby
rvm:
- 2.7
before_install:
- gem update --system
- gem install bundler
- gem install nypl_ruby_util
- pip install awscli
install:
- rake run_bundler
script:
- rake test
before_deploy:
- rm -rf vendor
- bundle install --without test
deploy:
- provider: lambda
  function_name: LocationsService-qa
  description: Service for fetching locations data by code
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  timeout: 15
  memory_size: 256
  module_name: app
  handler_name: handle_event
  environment:
    variables:
      LOG_LEVEL: info
      AWS_REGION: us-east-1
      BUCKET: locations-mapping-qa
      LOCATIONS_FILE: locations.json
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
- provider: lambda
  function_name: LocationsService-production
  description: Service for fetching locations data by code
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  timeout: 15
  memory_size: 256
  module_name: app
  handler_name: handle_event
  environment:
    variables:
      LOG_LEVEL: info
      AWS_REGION: us-east-1
      BUCKET: locations-mapping-production
      LOCATIONS_FILE: locations.json
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  on:
    branch: production
after_deploy:
- rake set_config
env:
  global:
  - secure: Qrg5WNweMmZB/6J0Fp734kWFz48VSsXNZ4hBAQvlC78SWDsAV659PaMB6QWa/FWkIg2LqkMhIFM/VtK8N4EyMalTeYzPtY4m5YffwO0hVvQTQ1+ph7VhwBBwyaYEF6G/MkrwejWLDdQ3TxkJQ08ACat7pFgvh0eVADGVTYYkKOGlRmFD9M8FGEyZl2axbvbdG54sf5MfoTlIZ/8DaweeOGVZYeRie7HUfn4gz8qFc+7/pHfsIcMPaJ7J8X8bn/7skuICafaZ2R6Mk06oKAfy8LyB0/dAVq2NX+S/EnWdHNHTvzD4A6Dzd7Ld39Zpa0QDQWZ3ycY3BafMdL2aHl+OyLX8VTCRi8QczZennf2NUfHZV0YSuHAY/UN0I8XnMCdIsX+DpbDP/zajvQpt6pV9++3Y4tkNPBTWVaRChJ5cyIkKOBgcRI43mOLzFAIewc6gakXHUjI77owA+0hlNBHQUUjjp1wMEtxsHayN0/kdbbvLE1IVstF0z4uyOJEpEcrubrNc982zPiDqDyy7/s1lAeF/1zb1w0q3x+yRsKPeK0EJBYbEgHJr7dO3VLW3eAHYbeSdl7mnchNcSCeMfz1KxEGkn9yaViOaJ7Lhs0RvnfwWJJ5Zwy/7OeYmnYlJe8jqq05fNQ8skGPT/cBalQxVAc5206vplvma5WzT40qxxfs=
  - secure: ZaRDmHlp3JiD6chrAq4iWNioPE12ekJ+k85qPSeC4CkZi5mTM+ox5BGrr18UhixL5D5yyyaw8tfOAOtfCezNgQfWm4o654+1dLpwKJ7vjaim1p5OB97BVx3/UIoHwI6znFvFmUTdgJiGt1WaQ6EcATLVLMHzwQo4BOMNQAv7yiQqSHL4hQ8jsCWax0MEsPDRH3u7L+6CMyxaG+ZQF/jordMh+aZrVIBm9NiQBDqFoWOiMQx30Jbc+L9VmhyHjfzL7+ZXPXXGvgip4z1yROnDvmsfny+ubDbmMnE5L7HXKFNF1hIIbQ5EAuXk6lmuFHhRB925dG3hZ14JcblPtRqcsnPd62bdTOMqtKLsNLqQ/TW30KdEiFEk6QTK9NEfgMNEyc3h8QjI2DL6j4RP/gQ7wJs5GSFUEZbWN6RkUGg9m1+pvoibAH9v84g6GtLHqBgAweIBE1rhe57OIn9RasMXj/2VwF6PcsQ4guQC3l1ltPZMpj8OysNDQWnOt5kGHKrf/rdvUDX3lax3NwliO18ulVCesz+ivK9amYzetUhxyH3RdSIL4zi3zj/slCGAC17S4QpI4jPxxgZEk0MUGg25bu2H8ty3KQANWuBFzYg0mbvlGac5SPf6PV6Tk2TXYEsIRiBA085mfXrecF6gRntEciRYAAudvFCp9NR0vIMJ2tE=
  - secure: o87T2Sr18SzgHw9ku1TpAhr6XsfjIOA37FpmAtt3N215JXDn1gFI2CYapYF9HQJ6FiTwuzTBYzkKqUuHaCDKwHcJiV8TGOaIjapbMsaIrMvYsDbQHh1NPvqau0gMuF7NDj8+macNr0TkNB2UNUcmTY1rgf+sLjVViUrPNaKXwoNf2Hr8PR/2coGcRconu4P42vqrSQ5PCld//aiX3iWjGfVjOaQ8bGGPbna4x+TR1ObD3RrOYsH16DdQsKhlxX7WOxPsXK9kKjD8U8caKEmRJxihUWZde7jUQjxkrMMynOl3O2gd7+umvt9e22xqKQsVlsgLXLl3+0WrRWUe0LaupY/SG6/7TqLOwTLKHiY7kJHwh6AyJAJm3/wiW40RpcAenzH94zoLUyGnnvy5spGVFyXxkaWrmWQqb+dAfOSh5gUSnPh1+yWNygWz6r3sOteM/U2vzZ3NvgabQNOgxcrAjEuOxupDmNhxfXhYjDOlmdWvyHsEW5Hcts1uzbtCfB/o7j/rkODiAOhIF1UqpBJbw4m2DpAlwyuLIw9AXMII1NCgX7AMZbX7XsI2zy90iFa9UnS46hFuLoQBWVUX1AeMnh1GX7/imat/2HGEE7f1G8yHuwWAHwAXcKd+UnZCQMHi/m3COiB68dPbB6AXAR7MZBJvOZ4RM/HkPDpexSpimnY=
