AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Function for returning locations data by code

Globals:
  Function:
    Timeout: 15
    Runtime: ruby2.7
    Handler: app.handle_event
    Environment:
      Variables:
        LOG_LEVEL: debug
        S3_AWS_REGION: us-east-1
        BUCKET: locations-mapping
        LOCATIONS_FILE: locations.json
        PROFILE: nypl-digital-dev

Resources:
  LocationsService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handle_event
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v0.1/locations
            Method: get
      Runtime: ruby2.7
      Timeout: 10
      Environment:
        Variables:
          NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com/nypl-core-objects-mapping-production/
          LOG_LEVEL: DEBUG
